# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AudioMixDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
#  use_frameworks!
   pod 'TheAmazingAudioEngine', '~> 1.5.8'


  # Pods for AudioMixDemo

  target 'AudioMixDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AudioMixDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
